# Generated by Django 3.2.6 on 2021-12-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=50)),
                ('fechaAlta', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCamas', models.IntegerField(help_text='Numero entre 1 y 4')),
                ('situacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrada', models.DateField(null=True)),
                ('fechaSalida', models.DateField(null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.cliente')),
                ('habitacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.habitacion')),
            ],
        ),
    ]
